# Generated by Django 5.0.14 on 2025-06-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
